frameworkVersion: "3"
service: database-replication

plugins:
  - serverless-vpc-discovery
  - serverless-plugin-utils
  - serverless-disable-functions

custom:
  enable_aurora:
    development: false
    staging: true

provider:
  name: aws
  region: eu-west-2
  stage: ${env:STAGE}
  timeout: 900

  deploymentBucket:
    name: "trade-tariff-lambda-deployment-${aws:accountId}"

  ecr:
    images:
      database-replication:
        uri: "${ssm:/${sls:stage}/DATABASE_REPLICATION_ECR_URL}:latest"

  environment:
    ENVIRONMENT: ${sls:stage}
    BASIC_AUTH_PASSWORD: ${env:BASIC_AUTH_PASSWORD}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - ecs:ListTasks
        - ecs:StartTask
        - ecs:StopTask
        - ecs:DescribeServices
        - ecs:UpdateService
      Resource:
        - "arn:aws:ecs:eu-west-2:${aws:accountId}:cluster/trade-tariff-cluster-*"
        - "arn:aws:ecs:eu-west-2:${aws:accountId}:task/trade-tariff-cluster-*"
        - "arn:aws:ecs:eu-west-2:${aws:accountId}:service/trade-tariff-cluster-*"
        - "arn:aws:ecs:eu-west-2:${aws:accountId}:container-instance/trade-tariff-cluster-*"

    - Effect: "Allow"
      Action:
        - secretsmanager:GetResourcePolicy
        - secretsmanager:GetSecretValue
        - secretsmanager:DescribeSecret
        - secretsmanager:ListSecretVersionIds
      Resource:
        - "arn:aws:secretsmanager:eu-west-2:${aws:accountId}:secret:tradetariffpostgres${sls:stage}-connection-string-*"
        - "arn:aws:secretsmanager:eu-west-2:${aws:accountId}:secret:aurora-postgres-rw-connection-string-*"

    - Effect: "Allow"
      Action:
        - kms:Encrypt
        - kms:Decrypt
        - kms:ReEncryptFrom
        - kms:ReEncryptTo
        - kms:GenerateDataKeyPair
        - kms:GenerateDataKeyPairWithoutPlainText
        - kms:GenerateDataKeyWithoutPlaintext
      Resource:
        - arn:aws:kms:eu-west-2:${aws:accountId}:alias/secretsmanager-key

functions:
  restore:
    image: database-replication
    environment:
      DATABASE_SECRET: "tradetariffpostgres${sls:stage}-connection-string"
    vpcDiscovery:
      vpcName: "trade-tariff-${sls:stage}-vpc"
      subnets:
        - tagKey: "Name"
          tagValues:
            - "*private*"
      securityGroups:
        - names:
            - "trade-tariff-be-rd-${sls:stage}"
            - "trade-tariff-alb-security-group-${sls:stage}"
    events:
      - schedule: cron(20 21 * * ? *) # Run every day at 21:20 UTC

  restore-aurora:
    enabled: ${self:custom.enable_aurora.${sls:stage}}

    image: database-replication
    environment:
      DATABASE_SECRET: "aurora-postgres-rw-connection-string"
    vpcDiscovery:
      vpcName: "trade-tariff-${sls:stage}-vpc"
      subnets:
        - tagKey: "Name"
          tagValues:
            - "*private*"
      securityGroups:
        - names:
            - "trade-tariff-be-rd-${sls:stage}"
            - "trade-tariff-alb-security-group-${sls:stage}"
    events:
      - schedule: cron(20 21 * * ? *) # Run every day at 21:20 UTC
