frameworkVersion: "3"
service: database-replication

plugins:
  - serverless-vpc-discovery
  - serverless-plugin-utils

provider:
  name: aws
  region: eu-west-2
  stage: ${env:STAGE}
  timeout: 900

  deploymentBucket:
    name: "trade-tariff-lambda-deployment-${aws:accountId}"

  ecr:
    images:
      database-replication:
        uri: "${ssm:/${sls:stage}/DATABASE_REPLICATION_ECR_URL}:latest"

  environment:
    ENVIRONMENT: ${sls:stage}
    POSTGRES_DATABASE: "TradeTariffPostgres${capitalize(${sls:stage})}"
    POSTGRES_HOST: ${env:POSTGRES_HOST}
    POSTGRES_PASSWORD: ${env:POSTGRES_PASSWORD}
    POSTGRES_USER: ${env:POSTGRES_USER}
    BASIC_AUTH_PASSWORD: ${env:BASIC_AUTH_PASSWORD}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - ecs:ListTasks
        - ecs:StartTask
        - ecs:StopTask
      Resource:
        - "arn:aws:ecs:eu-west-2:${aws:accountId}:cluster/trade-tariff-cluster-*"
        - "arn:aws:ecs:eu-west-2:${aws:accountId}:task/trade-tariff-cluster-*"
        - "arn:aws:ecs:eu-west-2:${aws:accountId}:service/trade-tariff-cluster-*"
        - "arn:aws:ecs:eu-west-2:${aws:accountId}:container-instance/trade-tariff-cluster-*"

functions:
  restore:
    image: database-replication
    vpcDiscovery:
      vpcName: "trade-tariff-${sls:stage}-vpc"
      subnets:
        - tagKey: "Name"
          tagValues:
            - "*private*"
      securityGroups:
        - names:
            - "trade-tariff-be-rd-${sls:stage}"
            - "trade-tariff-alb-security-group-${sls:stage}"
    events:
      - schedule: cron(20 21 * * ? *) # Run every day at 21:20 UTC
