version: 2.1

filter-not-main: &filter-not-main
  filters:
    branches:
      ignore:
        - main
        - /^dependabot/(?!docker/).*/
        - /^hotfix\/.+/

filter-main: &filter-main
  filters:
    branches:
      only:
        - main
        - /^hotfix\/.+/

orbs:
  serverless-framework: circleci/serverless-framework@2.0.1
  aws-cli: circleci/aws-cli@4.1.1

executors:
  default:
    docker:
      - image: cimg/node:lts
    resource_class: small

jobs:
  build:
    executor: default
    parameters:
      environment:
        type: string
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - aws-cli/install
      - run:
          name: "Build and Push to ECR"
          command: ./.circleci/ecr.sh "/<< parameters.environment >>/DATABASE_REPLICATION_ECR_URL"

  deploy:
    executor: default
    parameters:
      stage:
        type: string
    steps:
      - checkout
      - serverless-framework/setup
      - run: yarn
      - run:
          name: "Deploy Serverless"
          command: |
            STAGE=<< parameters.stage >> serverless deploy --verbose

workflows:
  version: 2

  deploy-to-development:
    jobs:
      - build:
          name: build-development
          environment: development
          context: trade-tariff-database-backups-development

      - deploy:
          name: deploy-development
          stage: development
          context: trade-tariff-database-backups-development
          requires:
            - build-development

  deploy-to-staging:
    jobs:
      - build:
          name: build-staging
          environment: staging
          context: trade-tariff-database-backups-staging

      - deploy:
          name: deploy-staging
          stage: staging
          context: trade-tariff-database-backups-staging
          requires:
            - build-staging
